name: Build Docker Test

on:
  pull_request:
    branches:
    - '**' 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker-image
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/azuki774/selenium-chrome
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
